name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Define a versão do Java que deseja utilizar

<<<<<<< HEAD
      - name: Build with Maven
        run: mvn clean install -B -V # Comando para realizar a build do projeto

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Define a versão do Java que deseja utilizar

      - name: Run tests with Maven
        run: mvn test # Comando para executar os testes do projeto
=======
      - name: Construir com Maven # Incluindo as dependencias
        run: mvn clean install -B -V

      - name: Executar testes # Executando os testes
        run: mvn test
>>>>>>> 6efc22e7d3c2818b1e7f865c92435acc3fe2454d
